# ............eth0.....................                                                                                                                                                                                                
WLAN_USER_IP=$(ifconfig eth0 | grep "inet addr" | grep -v "inet6" | awk -F: '{print $2}' | awk '{print $1}')                                                                                                                           
WLAN_USER_IPV6=$(ifconfig eth0 | grep "inet6 addr" | grep "Global" | awk '{print $3}' | cut -d/ -f1 )                                                                                                                                  
WLAN_USER_MAC=$(ifconfig eth0 | grep "HWaddr" | awk '{print $5}' | tr -d ':')                                                                                                                                                          
                                                                                                                                                                                                                                       
# ............                                                                                                                                                                                                                         
LOGIN_URL="http://10.254.7.4:801/eportal/portal/login"                                                                                                                                                                                 
USER_ACCOUNT="20221444"                                                                                                                                                                                                                
USER_PASSWORD="058778"                                                                                                                                                                                                                 
CALLBACK="dr1004&login_method=1"                                                                                                                                                                                                       
WLAN_AC_NAME="" # ........................                                                                                                                                                                                             
WLAN_AC_IP=""   # ........................                                                                                                                                                                                             
JS_VERSION="4.2"                                                                                                                                                                                                                       
TERMINAL_TYPE="1"                                                                                                                                                                                                                      
LANG="zh-cn"                                                                                                                                                                                                                           
V="5761"                                                                                                                                                                                                                               
                                                                                                                                                                                                                                       
# ..................                                                                                                                                                                                                                   
curl -G "$LOGIN_URL" \                                                                                                                                                                                                                 
    --data-urlencode "callback=$CALLBACK" \                                                                                                                                                                                            
    --data-urlencode "user_account=,0,${USER_ACCOUNT}" \                                                                                                                                                                               
    --data-urlencode "user_password=${USER_PASSWORD}" \                                                                                                                                                                                
    --data-urlencode "wlan_user_ip=${WLAN_USER_IP}" \                                                                                                                                                                                  
    --data-urlencode "wlan_user_ipv6=${WLAN_USER_IPV6}" \                                                                                                                                                                              
    --data-urlencode "wlan_user_mac=${WLAN_USER_MAC}" \                                                                                                                                                                                
    --data-urlencode "wlan_ac_name=${WLAN_AC_NAME}" \                                                                                                                                                                                  
    --data-urlencode "wlan_ac_ip=${WLAN_AC_IP}" \                                                                                                                                                                                      
    --data-urlencode "jsVersion=${JS_VERSION}" \                                                                                                                                                                                       
    --data-urlencode "terminal_type=${TERMINAL_TYPE}" \                                                                                                                                                                                
    --data-urlencode "lang=${LANG}" \                                                                                                                                                                                                  
    --data-urlencode "v=${V}" \                                                                                                                                                                                                        
    -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" \                                                                                   
    -H "Accept: */*" \                                                                                                                                                                                                                 
    -H "Referer: http://10.254.7.4/" \                                                                                                                                                                                                 
    -H "Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6" \                                                                                                                                                            
    -H "Connection: keep-alive"