#!/bin/bash                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
# ............                                                                                                                                                                                                                         
LOGIN_URL="http://10.254.7.4:801/eportal/portal/login"                                                                                                                                                                                 
USER_ACCOUNT="20221444"                                                                                                                                                                                                                
USER_PASSWORD="058778"                                                                                                                                                                                                                 
# WLAN_USER_IP="10.237.55.122"   
WLAN_USER_IP=$(ifconfig eth0 | grep "inet addr" | grep -v "inet6" | awk -F: '{print $2}' | awk '{print $1}')                                                                                                                                                                                                         
WLAN_USER_IPV6="2001:da8:c800:d237:68ba:4ff:fed8:927d"                                                                                                                                                                                 
WLAN_USER_MAC="6A:BA:04:D8:92:7D"                                                                                                                                                                                                      
CALLBACK="dr1004&login_method=1"                                                                                                                                                                                                       
                                                                                                                                                                                                                                       
# ..................                                                                                                                                                                                                                   
curl -X GET "$LOGIN_URL?callback=$CALLBACK&user_account=%2C0%2C${USER_ACCOUNT}&user_password=${USER_PASSWORD}&wlan_user_ip=${WLAN_USER_IP}&wlan_user_ipv6=${WLAN_USER_IPV6}&wlan_user_mac=${WLAN_USER_MAC}" \                          
    -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" \                                                                                   
    -H "Accept: */*" \                                                                                                                                                                                                                 
    -H "Referer: http://10.254.7.4/" \                                                                                                                                                                                                 
    -H "Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6" \                                                                                                                                                            
    -H "Connection: keep-alive"